### ISSUE TITLE
Targeting an h2

### ISSUE THREAD

**Issue by melissamcewen** [ThomasRipplinger/prj-rev-bwfs-dasmoto#2]
One neato thing is you can give this h2 a class to target or just target it directly, you don't need to wrap it in a div. 
https://github.com/ThomasRipplinger/prj-rev-bwfs-dasmoto/blob/master/DashmotosArts/index.html#L24-L26

this is a bit simpler and also takes advantage of an ID (https://css-tricks.com/the-difference-between-id-and-class/)

```html
        <h2 id="frames">Frames</h2>
```

```css
#frames {
    background-color: lightcoral;
}
```

you can also contain the whole thing in a div which has some advantages too in the next project

```html
  <div class="item">
    <h2 id="brush">Brushes</h2>
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg"/>
    <h3>Hacksaw Brushes</h3>
    <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="price">Starting at $3.00 / brush.</span></p>
  </div>

```

```css
.item h2 {
  font-size: 32px;
  color: white;
}

#brush {
  background-color: mediumspringgreen;
}
```
